spring.application.name=OficioYa
# Configuración de logs
logging.file.name=logs/oficioya.log
logging.level.root=INFO
logging.level.edu.eci.dosw.OficioYa=DEBUG
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
